function cp = CoverageProbability( sim, th )

pA = sim.ProbApBlocked( sim.distance2d,...
                     sim.distanceToTopHead,...
                     sim.apHeight,...
                     sim.distanceToUserBody,...
                     sim.bodyWide,...
                     sim.areaSide/2,...
                     sim.numberOfHumanBlockages );
prod1 = 1;
prod2 = 1;
illuminated = sim.distance2d < sim.mainLobeEdgeTx;
g = sim.DirectivityGain( ...
                        illuminated,...
                        sim.sideLobeGainTx,...
                        sim.mainLobeGainTx );
d = sim.PathLoss( ...
                sim.distance3d,...
                sim.p0_dB,...
                sim.attenuationExponent );
b = sim.bodyAttenuation;
[ ~, i] = min(sim.distance2d);
for j = 1:length(sim.distance2d)
    if j ~= i
    prod1 = prod1 * ...
        ( pA(j)/(1 + th*g(j)*d(j)/g(i)/d(i)) ...
        + (1-pA(j))/(1 + th*g(j)*d(j)/g(i)/d(i)/b) );
    prod2 = prod2 * ...
        ( pA(j)/(1 + th*b*g(j)*d(j)/g(i)/d(i)) ...
        + (1-pA(j))/(1 + th*g(j)*d(j)/g(i)/d(i)) );
    end
end
cp = pA(1) * prod1 + (1-pA(1)) * prod2;