beamwidth_id = 17;
bw_string = @(bwid) num2str(...
    rad2deg(beamWidth_vector(bwid)),...
    '%.f deg');
ca_string = { 'Max. Power' ; 'Min. Dist.';...
    'Fading Max. Power' ; 'Fading Min. Dist.'};
fixParam.height_id = 1;
fixParam.bodyAtt_id = 1;
fixParam.sinrThreshold = -5; %dB
fixParam.numBodies_id = 2; % 1 = one body, 2 = few bodies, 3 = many bodies
fixParam.distanceToBody_id = 2; % 1 = pocket, 2 = hand
out_DataProcessing;
ca = 4;

% patch positions
r0 = 0.8;
r1 = 2.5;
r2 = 8;
r3 = 30;
r4 = 100;
%% DRAW COVERAGE CURVES
figure(1);
clf(1);

% text region
t1 = annotation('textbox',...
    [0.13 0.11 0.19 0.82],...
    'String',{'I - high main-lobe interference'},...
    'LineStyle','none',...
    'FitBoxToText','off',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'BackgroundColor','none');
t2 = annotation('textbox',...
    [0.32 0.11 0.18 0.82],...
    'String',{'II - min. main-lobe interfence'},...
    'LineStyle','none',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'BackgroundColor','none');
t3 = annotation('textbox',...
    [0.50 0.11 0.2 0.82],...
    'String',{'III - high side-lobe interfence'},...
    'LineStyle','none',...
    'FitBoxToText','off',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'BackgroundColor','none');
t4 = annotation('textbox',...
    [0.7 0.11 0.2 0.82],...
    'String',{'IV - low interfence'},...
    'LineStyle','none',...
    'FitBoxToText','off',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'BackgroundColor','none');

% one beamwidth
h1 = semilogx( .5.*interSiteDistance_vector, ...
    100.*cov{ca}(beamwidth_id,:),...
    '-', 'Linewidth', 1.5);
hold on;

% background color
patch( [r0 r0 r1 r1], [0 102 102 0], [-1 -1 -1 -1], [.9 .9 .9], ...
    'LineStyle','none',...
    'FaceAlpha',.5);
patch( [r1 r1 r2 r2], [0 102 102 0], [-1 -1 -1 -1], [.8 .8 .8], ...
    'LineStyle','none',...
    'FaceAlpha',.5);
patch( [r2 r2 r3 r3], [0 102 102 0], [-1 -1 -1 -1], [.9 .9 .9], ...
    'LineStyle','none',...
    'FaceAlpha',.5);
patch( [r3 r3 r4 r4], [0 102 102 0], [-1 -1 -1 -1], [.8 .8 .8], ...
    'LineStyle','none',...
    'FaceAlpha',.5);

ylim([ 0 102 ]);
xlim( [ .8 100 ] );

xlabel('Half Inter-site Distance (m)');
ylabel( num2str( fixParam.sinrThreshold, 'Coverage SINR > %d dB (%%)'));
legend(h1,bw_string(beamwidth_id),...
    'Location','best');
grid on;
set(gca,'XMinorTick','on');
set(gca,'YMinorTick','on');
set(gca,'XMinorGrid','on');
set(gca,'YMinorGrid','on');
set(gca,'XTick',[1;2;5;10;20;50;100]);
set(gca,'XTickLabel',[1;2;5;10;20;50;100]);

% set(findall(gcf,'-property','FontSize'),'FontSize',13);
fig=gcf;
fig.OuterPosition = [100 100 600 400];
fig.Units = 'inches';
pos = fig.Position;
fig.PaperPositionMode = 'Auto'; 
fig.PaperUnits = 'inches'; 
fig.PaperSize = [pos(3),pos(4)];
print(fig,'figures/fig01_cov_behaviour','-dpdf','-r0');
%% DRAW SPECTRAL EFFICIENCY CURVES
figure(2);
clf(2);

% text region
t1 = annotation('textbox',...
    [0.13 0.11 0.19 0.82],...
    'String',{'I - high main-lobe interference'},...
    'LineStyle','none',...
    'FitBoxToText','off',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'BackgroundColor','none');
t2 = annotation('textbox',...
    [0.32 0.11 0.18 0.82],...
    'String',{'II - min. main-lobe interfence'},...
    'LineStyle','none',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'BackgroundColor','none');
t3 = annotation('textbox',...
    [0.50 0.11 0.2 0.82],...
    'String',{'III - high side-lobe interfence'},...
    'LineStyle','none',...
    'FitBoxToText','off',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'BackgroundColor','none');
t4 = annotation('textbox',...
    [0.7 0.11 0.2 0.82],...
    'String',{'IV - low interfence'},...
    'LineStyle','none',...
    'FitBoxToText','off',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'BackgroundColor','none');

% one beamwidth
h1 = loglog( .5.*interSiteDistance_vector,...
    ase{ca}(beamwidth_id,:),...
    '-', 'Linewidth', 1.5 );
hold on;

% background color
patch( [r0 r0 r1 r1], [1e-5 2 2 1e-5], [-1 -1 -1 -1], [.9 .9 .9], ...
    'LineStyle','none',...
    'FaceAlpha',.5);
patch( [r1 r1 r2 r2], [1e-5 2 2 1e-5], [-1 -1 -1 -1], [.8 .8 .8], ...
    'LineStyle','none',...
    'FaceAlpha',.5);
patch( [r2 r2 r3 r3], [1e-5 2 2 1e-5], [-1 -1 -1 -1], [.9 .9 .9], ...
    'LineStyle','none',...
    'FaceAlpha',.5);
patch( [r3 r3 r4 r4], [1e-5 2 2 1e-5], [-1 -1 -1 -1], [.8 .8 .8], ...
    'LineStyle','none',...
    'FaceAlpha',.5);

ylim([ 1e-5 2 ]);
xlim( [ .8 100 ] );

xlabel('Half Inter-site Distance (m)');
ylabel( 'Area Spectral Efficiency (bps/Hz/m2) ');
legend(h1,bw_string(beamwidth_id),...
    'Location','best');
grid on;
set(gca,'XMinorTick','on');
set(gca,'YMinorTick','on');
set(gca,'XMinorGrid','on');
set(gca,'YMinorGrid','on');
set(gca,'XTick',[1;2;5;10;20;50;100]);
set(gca,'XTickLabel',[1;2;5;10;20;50;100]);

% set(findall(gcf,'-property','FontSize'),'FontSize',13);
clear fig;
fig=gcf;
fig.OuterPosition = [100 100 600 400];
fig.Units = 'inches';
pos = fig.Position;
fig.PaperPositionMode = 'Auto'; 
fig.PaperUnits = 'inches'; 
fig.PaperSize = [pos(3),pos(4)];
print(fig,'figures/fig02_ase_behaviour','-dpdf','-r0');