ca_id = 2;
h_id = 1;
isd = interSiteDistance_vector;
st = 0;
sinr_threshold = db2pow( st );

for db_id = 1:length(distanceToUserBody_vector)
    % sinr vector
    s = squeeze( sinrv{ca_id}( :,:,h_id,:,:,:,db_id ) ); % 10000 50 101
    
    % coverage
    cov = sum( s > sinr_threshold, 1 ) ./ numberOfIterations;
    cov = squeeze( cov );

    % spectral efficiency
    n_se = log2( 1 + s );
    avg_se = squeeze( mean( n_se, 1 ) );
    cellarea = repmat((2*sqrt(3).*(.5.*isd).^2),length(beamWidth_vector),1);
    ase = avg_se ./ cellarea;

    % envelope
    [ max_ss(:,db_id), s_isd(:,db_id) ] = max( ase, [], 2 );
    [ max_cc(:,db_id), c_isd(:,db_id) ] = max( cov, [], 2 );
    map_cc(db_id,:) = diag( cov( :, s_isd(:,db_id) ) )';

    for bw_id = 1:length(beamWidth_vector)
        c_isd( bw_id, db_id ) = find( cov(bw_id,:) == max_cc(bw_id,db_id), 1, 'last' );
    end
    map_ss(db_id,:) = diag( ase( :, c_isd(:,db_id) ) )';
end

%%
figure(30);
clf(30);
set( gca, 'ColorOrder', lines(length(distanceToUserBody_vector)), 'NextPlot', 'replacechildren' );

for db_id = [ 1 2 3 4 5 ]
    h = semilogy( 100.*max_cc(6:end-10,db_id), map_ss(db_id,6:end-10), ...
        'MarkerSize',15,...
        'Marker','.',...
        'Linewidth',2);
    hold on;
end

title( num2str( apHeight_vector(h_id), 'AP %gm above UE' ) );
legend( 'B = -40 dB, pocket', ...
    'B = -40 dB, hand 05 cm', ...
    'B = -40 dB, hand 15 cm', ...
    'B = -40 dB, hand 30 cm', ...
    'B = 0 dB, no body att', ...
    'Location', 'west');

xlim([ 0 102 ]);
ylim( [ 5e-5 1.5 ] );
ylabel('Achieved Area Spectral Efficiency (bps/Hz/m2)');
xlabel( num2str( st, 'Optimized Coverage SINR > %d dB (%%)'));
grid on;
set(gca,'XMinorTick','on');
set(gca,'YMinorTick','on');
set(gca,'XMinorGrid','on');
set(gca,'YMinorGrid','on');

bw_id = 20;
db_id = 1;
plot(100.*max_cc(bw_id,db_id), map_ss(db_id,bw_id),'hk');
text( 100.*max_cc(bw_id,db_id), map_ss(db_id,bw_id), ...
        { ...
        num2str( isd(c_isd(bw_id,db_id)), 'd_S = %.3g m \n' ); ...
        strcat( ' \Theta_{BW}', ...
                num2str( rad2deg(beamWidth_vector(bw_id)), ' = %.0f '), ...
                '\circ' ) ...
        } ...
    );
bw_id = 17;
db_id = 4;
plot(100.*max_cc(bw_id,db_id), map_ss(db_id,bw_id),'hk');
text( 100.*max_cc(bw_id,db_id), map_ss(db_id,bw_id), ...
        { ...
        num2str( isd(c_isd(bw_id,db_id)), 'd_S = %.3g m \n' ); ...
        strcat( ' \Theta_{BW}', ...
                num2str( rad2deg(beamWidth_vector(bw_id)), ' = %.0f '), ...
                '\circ' ) ...
        } ...
    );

bw_id = 38;
db_id = 1;
plot(100.*max_cc(bw_id,db_id), map_ss(db_id,bw_id),'hk');
text( 100.*max_cc(bw_id,db_id), map_ss(db_id,bw_id), ...
        { ...
        num2str( isd(c_isd(bw_id,db_id)), 'd_S = %.3g m \n' ); ...
%         strcat( ' \Theta', ...
%                 num2str( rad2deg(beamWidth_vector(bw_id)), ' = %.0f '), ...
%                 '\circ' ) ...
        } ...
    );
bw_id = 38;
db_id = 4;
plot(100.*max_cc(bw_id,db_id), map_ss(db_id,bw_id),'hk');
text( 100.*max_cc(bw_id,db_id), map_ss(db_id,bw_id), ...
        { ...
        num2str( isd(c_isd(bw_id,db_id)), 'd_S = %.3g m \n' ); ...
%         strcat( ' \Theta', ...
%                 num2str( rad2deg(beamWidth_vector(bw_id)), ' = %.0f '), ...
%                 '\circ' ) ...
        } ...
    );

% Create rectangle
annotation('rectangle',...
    [0.52 0.6 0.41 0.3],...
    'Color',[0.50 0.50 0.50],...
    'LineStyle','--');
annotation('textbox',...
    [0.62 0.63 0.41 0.26],...
    'String','high density',...
    'LineStyle','none');
annotation('textbox',...
    [0.51 0.13 0.41 0.1],...
    'String','low density',...
    'LineStyle','none');
annotation('ellipse',...
    [0.62 0.30 0.29 0.25],...
    'Color',[0.50 0.50 0.50],...
    'LineStyle','--');


set(findall(gcf,'-property','FontSize'),'FontSize',12);